version: '3'

services:
  mongodb:
    image: mongo:jammy
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password