apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedservice
  labels:
    app: feedservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedservice
  template:
    metadata:
      labels:
        app: feedservice
    spec:
      volumes:
        - name: google-cloud-keys
          secret:
            secretName: gac-key
      containers:
        - name: feedservice
          image: us-east1-docker.pkg.dev/sonarqube-289802/competency-insights/feed-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
              protocol: TCP
          volumeMounts:
            - name: google-cloud-keys
              mountPath: /var/secrets/google
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          envFrom:
            - configMapRef:
                name: contribution-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: feedservice
  labels:
    app: feedservice
spec:
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: feedservice
  type: LoadBalancer

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: feedservice-configmap
data:
  ACTIVE_PROFILE: gcp
  SERVICE_NAME: Feed Service
  GCP_PROJECT_ID: sonarqube-289802
  PUB_SUB_TOPIC: nasher.info
