# This is a deployment for the contributionservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contributionservice
  labels:
    app: contributionservicetest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contributionservice
  template:
    metadata:
      labels:
        app: contributionservice
    spec:
      containers:
        - name: contributionservice
          image: us-east1-docker.pkg.dev/sonarqube-289802/competency-insights/contribution-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: contribution-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: contributionservice
  labels:
    app: contributionservice
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: contributionservice
  type: LoadBalancer

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: contribution-configmap
data:
  ACTIVE_PROFILE: gcp
  GCP_PROJECT_ID: sonarqube-289802
  PUB_SUB_TOPIC: nasher.info